/**
 * handshake/handshake.ts - X3DH handshake state machine.
 *
 * Implements a simplified X3DH (Extended Triple Diffie-Hellman) handshake
 * for establishing a Double Ratchet session between Alice and Bob.
 *
 * Flow:
 *   Alice (initiator)                          Bob (responder)
 *   ─────────────────                          ───────────────
 *   1. Fetch Bob's DME pub key
 *      from DID document
 *   2. Generate ephemeral X25519
 *      key pair
 *   3. sharedSecret = X25519(
 *        ephemeralPriv,
 *        Bob_identityPub)
 *   4. queueId1 = deriveQueueId(
 *        ephemeralPub, 0, sharedSecret)
 *   5. Construct HandshakePayload
 *   6. Encode as QR code
 *   ─────── QR scan ──────────────>           7. Decode QR code
 *                                              8. sharedSecret = X25519(
 *                                                   self_identityPriv,
 *                                                   ephemeralPub)
 *                                              9. Init DoubleRatchet as
 *                                                 receiver
 *                                             10. Post QueueID_1 envelope
 *   11. Detect QueueID_1 via
 *       firehose
 *   12. Init DoubleRatchet as
 *       sender
 *
 * The identityPubHash field prevents man-in-the-middle attacks: Bob can
 * verify that the QR code was generated by the DID he expects.
 */

import { x25519 } from '@noble/curves/ed25519';
import { sha256 } from '@noble/hashes/sha256';
import { bytesToHex, utf8ToBytes } from '@noble/hashes/utils';

import { computeSharedSecret } from '../crypto/identity';
import { DoubleRatchet } from '../crypto/ratchet';
import { deriveQueueId } from '../crypto/queue-id';
import { QUEUEID_SALT } from '../crypto/constants';
import type { DmeDidManager } from '../atproto/did';
import type { IdentityKey } from '../crypto/identity';
import type { DmeStorage } from '../storage/db';

/**
 * Handshake payload encoded in the QR code.
 *
 * All fields except identityPubHash are needed to establish the
 * encrypted session. identityPubHash is for MITM detection.
 */
export interface HandshakePayload {
  /** Protocol version (always 1 for now). */
  version: 1;
  /** Alice's DID, so Bob can fetch her identity public key. */
  aliceDid: string;
  /** Alice's ephemeral X25519 public key (32 bytes, base64url encoded). */
  ephemeralPub: string;
  /** SHA-256 hash of Alice's identity public key (hex, for MITM detection). */
  identityPubHash: string;
  /** First message QueueID (hex string). */
  queueId1: string;
  /** ISO 8601 timestamp of when the QR code was generated. */
  createdAt: string;
}

/**
 * Cached state between initiate() and initSenderRatchet().
 *
 * Alice cannot initialize her sender DoubleRatchet until Bob's QueueID_1
 * response arrives. The ephemeral private key, Bob's public key, the shared
 * secret, and queueId1 are persisted to DmeStorage so they survive across
 * app restarts. All byte fields are base64url-encoded for JSON storage.
 */
interface PendingHandshake {
  ephemeralPrivB64: string;
  remotePubKeyB64: string;
  sharedSecretB64: string;
  queueId1: string;
}

/**
 * Result of accepting a handshake (Bob's side).
 */
export interface AcceptResult {
  ratchet: DoubleRatchet;
  queueId1: string;
  sharedSecret: Uint8Array;
  initialQueueId: string;
}

/**
 * Manages the X3DH handshake for establishing encrypted conversations.
 *
 * One instance per handshake attempt. After accept/initiate completes,
 * use the returned DoubleRatchet for ongoing communication.
 */
export class DmeHandshake {
  /** Alice's identity key (for initiating). */
  private readonly identityKey: IdentityKey;

  /** DID manager for fetching remote encryption keys. */
  private readonly didManager: DmeDidManager;

  /** Persistent storage for pending handshake state. */
  private readonly storage: DmeStorage;

  constructor(
    identityKey: IdentityKey,
    didManager: DmeDidManager,
    storage: DmeStorage,
  ) {
    this.identityKey = identityKey;
    this.didManager = didManager;
    this.storage = storage;
  }

  /**
   * Alice's side: initiate a handshake with a remote user.
   *
   * Steps:
   *   1. Fetch Bob's DME encryption public key from his DID document
   *   2. Generate an ephemeral X25519 key pair
   *   3. Compute sharedSecret = X25519(ephemeralPriv, Bob_identityPub)
   *   4. Derive queueId1 from the ephemeral public key and shared secret
   *   5. Compute identityPubHash for MITM detection
   *   6. Cache ephemeralPriv + remotePubKey + sharedSecret + queueId1 to
   *      storage so initSenderRatchet() can run after Bob responds
   *   7. Return HandshakePayload (to be encoded as QR code)
   *
   * The DoubleRatchet is NOT initialized here. Alice initializes it as a
   * sender only after detecting Bob's QueueID_1 response via firehose,
   * by calling initSenderRatchet().
   *
   * @param remoteDid - Bob's DID (e.g., "did:plc:...").
   * @param localDid  - Alice's own DID (included in payload so Bob can
   *                    fetch her identity public key for MITM check).
   * @returns HandshakePayload to encode in a QR code.
   */
  async initiate(
    remoteDid: string,
    localDid: string,
  ): Promise<HandshakePayload> {
    // 1. Fetch Bob's encryption public key from his DID document
    const remotePubKey = await this.didManager.getRemoteEncryptionKey(remoteDid);

    // 2. Generate ephemeral X25519 key pair
    const ephemeralPriv = x25519.utils.randomPrivateKey();
    const ephemeralPub = x25519.getPublicKey(ephemeralPriv);

    // 3. Compute shared secret
    const sharedSecret = computeSharedSecret(ephemeralPriv, remotePubKey);

    // 4. Derive queueId1: the first QueueID for the conversation
    const queueId1 = deriveQueueId(ephemeralPub, 0, sharedSecret);

    // 5. Compute identity public key hash for MITM detection
    const identityPubHash = bytesToHex(
      sha256(concatBytes(utf8ToBytes(QUEUEID_SALT), this.identityKey.publicKey)),
    );

    // 6. Cache state for initSenderRatchet() (keyed by remoteDid)
    const pending: PendingHandshake = {
      ephemeralPrivB64: bytesToBase64url(ephemeralPriv),
      remotePubKeyB64: bytesToBase64url(remotePubKey),
      sharedSecretB64: bytesToBase64url(sharedSecret),
      queueId1,
    };
    await this.storage.putRaw(
      'handshake:pending:' + remoteDid,
      JSON.stringify(pending),
    );

    // 7. Return payload for QR encoding
    return {
      version: 1,
      aliceDid: localDid,
      ephemeralPub: bytesToBase64url(ephemeralPub),
      identityPubHash,
      queueId1,
      createdAt: new Date().toISOString(),
    };
  }

  /**
   * Initialize Alice's Double Ratchet as sender after detecting Bob's
   * QueueID_1 response.
   *
   * Reads the cached handshake state (sharedSecret, remotePubKey) written
   * by initiate(), calls DoubleRatchet.initSender, then deletes the cache
   * so it cannot be replayed.
   *
   * @param remoteDid - Bob's DID (the key under which state was cached).
   * @returns Initialized Double Ratchet ready to encrypt.
   * @throws if no pending handshake exists for remoteDid.
   */
  async initReceiverRatchet(remoteDid: string): Promise<DoubleRatchet> {
    const raw = await this.storage.getRaw('handshake:pending:' + remoteDid);
    if (!raw) {
      throw new Error(
        'DmeHandshake.initReceiverRatchet: no pending handshake for ' + remoteDid,
      );
    }

    const pending = JSON.parse(raw) as PendingHandshake;
    const sharedSecret = base64urlToBytes(pending.sharedSecretB64);
    const ephemeralPriv = base64urlToBytes(pending.ephemeralPrivB64);
    const ephemeralPub = x25519.getPublicKey(ephemeralPriv);
    return DoubleRatchet.initReceiver(sharedSecret, ephemeralPriv);
  }

  async deletePendingHandshake(remoteDid: string): Promise<void> {
    await this.storage.deleteRaw('handshake:pending:' + remoteDid);
  }

  /**
   * Bob's side: accept a handshake from a scanned QR code.
   *
   * Steps:
   *   1. Fetch Alice's identity public key from her DID document
   *   2. Verify identityPubHash matches (MITM detection)
   *   3. Compute sharedSecret = X25519(self_identityPriv, ephemeralPub)
   *   4. Initialize Double Ratchet as receiver
   *   5. Return ratchet + queueId1 (for posting the response envelope)
   *
   * @param payload - The decoded HandshakePayload from the QR code.
   * @returns Initialized ratchet and queueId1.
   * @throws if identityPubHash does not match Alice's DID-published key.
   */
  async accept(payload: HandshakePayload): Promise<AcceptResult> {
    // 1. Fetch Alice's identity public key from her DID document
    const alicePub = await this.didManager.getRemoteEncryptionKey(
      payload.aliceDid,
    );

    // 2. Verify identityPubHash (MITM detection): the hash must match
    //    Alice's DID-published key, not Bob's own key.
    const expectedHash = bytesToHex(
      sha256(concatBytes(utf8ToBytes(QUEUEID_SALT), alicePub)),
    );
    if (expectedHash !== payload.identityPubHash) {
      throw new Error(
        'MITM detected: identityPubHash mismatch for ' + payload.aliceDid,
      );
    }

    const ephemeralPub = base64urlToBytes(payload.ephemeralPub);
    const sharedSecret = computeSharedSecret(
      this.identityKey.privateKey,
      ephemeralPub,
    );

    const ratchet = DoubleRatchet.initSender(
      sharedSecret,
      this.identityKey.privateKey,
      ephemeralPub,
      payload.queueId1,
    );

    const initialQueueId = deriveQueueId(ephemeralPub, 1, sharedSecret);

    return {
      ratchet,
      queueId1: payload.queueId1,
      sharedSecret,
      initialQueueId,
    };
  }
}

// ---------------------------------------------------------------------------
// Helper functions
// ---------------------------------------------------------------------------

/** Concatenate multiple Uint8Arrays into one. */
function concatBytes(...arrays: Uint8Array[]): Uint8Array {
  let totalLength = 0;
  for (const arr of arrays) {
    totalLength += arr.length;
  }
  const result = new Uint8Array(totalLength);
  let offset = 0;
  for (const arr of arrays) {
    result.set(arr, offset);
    offset += arr.length;
  }
  return result;
}

/** Convert Uint8Array to base64url string. */
function bytesToBase64url(bytes: Uint8Array): string {
  let binary = '';
  for (let i = 0; i < bytes.length; i++) {
    binary += String.fromCharCode(bytes[i]!);
  }
  return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

/** Convert base64url string to Uint8Array. */
function base64urlToBytes(str: string): Uint8Array {
  const base64 = str.replace(/-/g, '+').replace(/_/g, '/');
  const padded = base64 + '='.repeat((4 - (base64.length % 4)) % 4);
  const binary = atob(padded);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}
